const fs = require('fs');
const answersData = JSON.parse(fs.readFileSync('./answers.js', 'utf8').replace('const answersData = ', '').trim().replace(/;$/, ''));

const n = {
"rm-3-2tzrss": "# Ethical Concerns of Automated Plagiarism Detection Tools\n\nAutomated plagiarism detection tools (like Turnitin or iThenticate) are widely used, but they raise several ethical concerns:\n\n1. **False Positives:** The software often flags common phrases, bibliographies, or properly quoted material as \"plagiarized.\" This can lead to unjust accusations against students or researchers, damaging their reputations.\n2. **Intellectual Property/Copyright:** Many tools store uploaded documents in their massive proprietary databases to check against future submissions. Critics argue this is a violation of the author's copyright, as the company profits from content they do not own without the author's explicit consent.\n3. **Lack of Context:** Software cannot understand intent. It cannot distinguish between malicious theft of ideas and a student struggling with poor paraphrasing skills. It reduces a complex pedagogical issue to a simple percentage score.\n4. **Presumption of Guilt:** Routine use of these tools can create an adversarial environment where students feel they are presumed guilty until the machine proves them innocent, undermining trust between educators and learners.\n5. **Data Privacy:** Storing student papers on commercial servers raises concerns about data privacy and security.",

"rm-3-783jgn": "# Moral Judgments and Reactions: Subjective vs Objective\n\n### Nature of Moral Judgments:\nMoral judgments are evaluations or opinions formed as to whether some action or inaction, intention, motive, character trait, or person as a whole is (more or less) Good or Bad. They involve applying a moral standard to a specific situation.\n\n### Subjective Moral Judgments:\n- **Definition:** The view that moral judgments are statements about the speaker's feelings, attitudes, or cultural norms. They are true or false *relative* to the individual or society.\n- **Characteristics:** \"Stealing is wrong\" translates to \"I disapprove of stealing\" or \"My culture forbids stealing.\" There is no universal, independent moral truth.\n- **Example:** In one culture, eating a certain animal is a moral offense; in another, it is accepted. Both are \"right\" within their own subjective frameworks.\n\n### Objective Moral Judgments:\n- **Definition:** The view that moral judgments refer to facts about the world that exist independently of human thought or feelings.\n- **Characteristics:** \"Stealing is wrong\" is a statement of objective fact, similar to \"The Earth is round.\" It is universally true or false, regardless of whether anyone believes it or not.\n- **Example:** Human rights abuses are objectively wrong everywhere, regardless of a specific culture's attitude toward them.",

"rm-3-i6wzru": "# Importance of Intellectual Honesty and Ethical Responsibility\n\nIntellectual honesty and ethical responsibility are the bedrock of the scientific enterprise.\n\n1. **Trust in the Scientific Record:** Science builds upon previous discoveries. If researchers are intellectually dishonest (e.g., falsifying data), the foundation of subsequent research is corrupted, leading to wasted time, resources, and potentially dangerous outcomes.\n2. **Public Trust and Funding:** The public funds research through taxes and relies on scientific findings for policy, healthcare, and technology. Ethical breaches destroy public trust, which can lead to decreased funding and skepticism of science (e.g., the anti-vaccine movement fueled by fraudulent research).\n3. **Protection of Subjects:** Ethical responsibility ensures that human and animal subjects are treated humanely, their rights and privacy are protected, and they are not subjected to unnecessary harm (e.g., following guidelines set after historical ethical failures like the Tuskegee Syphilis Study).\n4. **Fair Allocation of Credit:** Intellectual honesty ensures that researchers receive proper credit for their ideas and hard work, which is essential for career advancement and academic integrity.\n5. **Progress of Knowledge:** Honest reporting of negative results (when an experiment fails) is just as important as reporting successes, as it prevents others from repeating the same dead-end experiments.",

"rm-4-5h56i8": "# Data Processing and Analysis Steps\n\n1. **Editing:** The first step involves checking the collected raw data (e.g., survey questionnaires) for errors, omissions, inconsistencies, and illegibility. The goal is to ensure data quality and accuracy before analysis. \n   - *Example:* Checking if a respondent selected two conflicting options on a survey and deciding how to handle that response.\n2. **Coding:** Assigning numerical scores or other symbols to responses so they can be entered into a computer or database. It transforms qualitative or categorical data into a format suitable for statistical analysis.\n   - *Example:* Assigning \"1\" for Male, \"2\" for Female, and \"3\" for Prefer not to say.\n3. **Tabulation:** Summarizing the raw data and displaying it in a compact, organized form (usually tables). It involves counting the number of cases falling into different categories.\n   - *Example:* Creating a frequency table showing how many people chose \"Strongly Agree\" vs \"Disagree.\"\n4. **Analysis:** The computation of certain measures along with searching for patterns of relationship that exist among data groups. This involves applying statistical tools (descriptive and inferential statistics) to test hypotheses and draw conclusions.",

"rm-4-oibwrk": "# Null Hypothesis and Type I / Type II Errors\n\n### Significance of Null Hypothesis ($H_0$):\nThe Null Hypothesis is the default assumption that there is **no significant difference**, **no effect**, or **no relationship** between variables. In statistical testing, we always test the null hypothesis, attempting to find enough evidence to reject it in favor of the Alternative Hypothesis ($H_1$). It acts as the \"innocent until proven guilty\" baseline.\n\n### Type I Error (False Positive):\n- **Definition:** Rejecting the null hypothesis when it is actually true.\n- **Meaning:** You conclude there *is* an effect or difference when, in reality, there isn't one. (Convicting an innocent person).\n- **Probability:** Denoted by Alpha ($\\alpha$), which is the significance level (usually 0.05 or 5%).\n\n### Type II Error (False Negative):\n- **Definition:** Failing to reject the null hypothesis when it is actually false.\n- **Meaning:** You conclude there is *no* effect or difference when, in reality, there is one. (Letting a guilty person go free).\n- **Probability:** Denoted by Beta ($\\beta$).",

"rm-4-xkhkxs": "# The Process of Hypothesis Testing\n\n### Flow Diagram/Steps:\n\n1. **State the Hypotheses:**\n   - Formulate the Null Hypothesis ($H_0$: No effect/difference).\n   - Formulate the Alternative Hypothesis ($H_1$: There is an effect/difference).\n2. **Select the Level of Significance ($\\alpha$):**\n   - Choose the probability of making a Type I error (commonly 0.05 or 5%).\n3. **Choose the Appropriate Statistical Test:**\n   - Based on data type (categorical/continuous), distribution (normal/non-normal), and sample size (e.g., t-test, ANOVA, Chi-square).\n4. **Determine the Critical Region (Rejection Region):**\n   - Identify the critical values from statistical tables based on $\\alpha$ and degrees of freedom.\n5. **Compute the Test Statistic:**\n   - Calculate the value using the sample data and the formula for the chosen test.\n6. **Make a Decision:**\n   - Compare the calculated test statistic to the critical value (or compare the p-value to $\\alpha$).\n   - If the calculated value falls in the critical region (or p-value < $\\alpha$), **Reject $H_0$**.\n   - Otherwise, **Fail to Reject $H_0$**.\n7. **Draw Conclusions:** Interpret the statistical decision in the context of the real-world research problem.",

"rm-4-1zck5i": "# Data Collection, Processing, and Analysis Example\n\n**Scenario:** A company wants to know if a new training program improves employee sales performance.\n\n1. **Data Collection:**\n   - The researcher selects a sample of 100 employees.\n   - *Primary Data:* Records their average monthly sales before the training.\n   - After the training, records their average monthly sales again.\n2. **Data Processing:**\n   - **Editing:** Checks the spreadsheets to ensure all 100 employees have both \"before\" and \"after\" data. Removes two employees who quit mid-study.\n   - **Coding:** Assigns ID numbers (1-98) to anonymize the data.\n   - **Tabulation:** Enters the data into a statistical software package (like SPSS or Excel) in columns: `Employee_ID`, `Sales_Before`, `Sales_After`.\n3. **Data Analysis:**\n   - Computes descriptive statistics (mean sales before = $10,000; mean sales after = $12,000).\n   - Applies an inferential statistical test (e.g., a Paired Samples t-test) to see if the $2,000 difference is statistically significant or just due to random chance.\n   - Result: The test shows a significant increase, leading to the conclusion that the training is effective.",

"rm-4-67tyeo": "# P-value in Statistical Hypothesis Testing\n\n### Concept of p-value:\nThe **p-value** (probability value) is a number describing how likely it is that your data would have occurred by random chance if the null hypothesis were true.\n- It measures the strength of evidence against the null hypothesis.\n- **Smaller p-value** $\\rightarrow$ stronger evidence against $H_0$ (meaning the result is highly unlikely to be random chance).\n- **Larger p-value** $\\rightarrow$ weaker evidence against $H_0$.\n\n### Common Thresholds (Alpha Level $\\alpha$):\nThe threshold used to decide if the p-value is small enough to reject the null hypothesis is called the significance level ($\\alpha$).\n\n- **$\\alpha = 0.05$ (5%):** The standard threshold in most scientific research. If p < 0.05, the result is considered \"statistically significant\" (reject $H_0$). It means there is less than a 5% probability the result happened by chance.\n- **$\\alpha = 0.01$ (1%):** Used in stricter fields like medicine. Provides stronger evidence.\n- **$\\alpha = 0.10$ (10%):** Sometimes used in exploratory research where a higher risk of false positives is acceptable.\n\n*Rule of thumb:* \"If p is low, $H_0$ must go.\"",

"rm-4-856bu7": "# Hypothesis Testing Calculation Example\n\n**Given:**\n- Population Mean ($\\mu_0$) = 3 hrs (Claim)\n- Sample Mean ($\\bar{x}$) = 3.5 hrs\n- Standard Deviation ($\\sigma$) = 0.8 hrs\n- Sample Size ($n$) = 50\n- Significance Level ($\\alpha$) = 0.05\n\n**Step 1: State Hypotheses**\n- $H_0$: $\\mu \\le 3$ (Average time is 3 hours or less)\n- $H_1$: $\\mu > 3$ (Average time is greater than 3 hours - Right-tailed test)\n\n**Step 2: Choose Test**\nSince $n > 30$, we use the **Z-test**.\n\n**Step 3: Calculate Test Statistic (Z)**\n$$Z = \\frac{\\bar{x} - \\mu_0}{\\sigma / \\sqrt{n}} = \\frac{3.5 - 3}{0.8 / \\sqrt{50}} = \\frac{0.5}{0.8 / 7.07} = \\frac{0.5}{0.113} = 4.42$$\n\n**Step 4: Determine Critical Value**\nFor a right-tailed test at $\\alpha = 0.05$, the critical Z-value is **1.645**.\n\n**Step 5: Decision and Conclusion**\nSince the calculated Z-value (4.42) is much greater than the critical value (1.645), it falls in the rejection region.\n**Conclusion:** Reject $H_0$. There is sufficient evidence at the 5% significance level to support the claim that the average social media time is greater than 3 hours.",

"rm-5-l2q84t": "# Web of Science vs Scopus\n\nBoth are major multidisciplinary citation databases used for literature review and tracking academic impact, but they have key differences:\n\n| Feature | Web of Science (WoS) | Scopus |\n| :--- | :--- | :--- |\n| **Publisher** | Clarivate Analytics | Elsevier |\n| **Coverage/Size** | Smaller, highly curated list of journals. Focuses on older, established publications. | Larger, broader coverage. Includes more recent journals and proceedings. |\n| **Subject Focus** | Very strong in exact sciences and traditional disciplines. | Stronger in social sciences, humanities, and technology/engineering. |\n| **Metrics** | Provides the official **Journal Impact Factor (JIF)**. | Provides **CiteScore**, SJR, and SNIP. |\n| **Selectivity** | Extremely strict inclusion criteria; considered the \"gold standard\" for prestige. | Less strict than WoS, but still rigorously peer-reviewed. |\n| **History** | Older database, traces citations back further (to 1900). | Newer (launched 2004), citation tracking is strongest post-1996. |",

"rm-5-axro0n": "# Reference Management Tools (Zotero, Mendeley, EndNote)\n\n### What are they?\nReference management software tools help researchers organize, store, and manage their literature sources and automatically generate citations and bibliographies in their written work.\n\n### How they are used in research:\n1. **Collecting Sources:** They offer browser extensions that allow researchers to save papers, web pages, and metadata (authors, journal, date) directly from databases (like Google Scholar or PubMed) with a single click.\n2. **Organizing:** Researchers can create folders, tag articles, and search their personal library. Many tools allow PDF storage and in-app highlighting/annotating.\n3. **Formatting Citations:** Plugins integrate the tool directly into Word processors (like MS Word or Google Docs). As the researcher writes, they insert citations. The tool automatically formats the in-text citation and builds the bibliography at the end.\n4. **Changing Styles instantly:** If a journal rejects a paper formatted in APA, the researcher can use the tool to instantly reformat the entire document to IEEE or MLA style with one click.\n5. **Collaboration:** Tools like Mendeley and Zotero allow sharing libraries with co-authors.",

"rm-5-qclvnx": "# Referencing, Footnotes, and Bibliography\n\n### Importance in Research:\n1. **Giving Credit:** Proper referencing acknowledges the original authors whose ideas, theories, or data you have used, preventing plagiarism.\n2. **Verifiability:** It allows readers (and reviewers) to trace your sources, verify the accuracy of your claims, and evaluate the quality of your evidence.\n3. **Contextualizing:** It demonstrates that your research is built upon a solid foundation of existing literature and shows how your work fits into the broader academic conversation.\n\n### Differences:\n- **Referencing (In-text citations):** Brief markers within the main text (e.g., \"Smith, 2020\" or \"[1]\") indicating that the information was drawn from another source.\n- **Footnotes:** Notes placed at the bottom of the page. They can be used for citations (in styles like Chicago) or to provide additional explanatory text or commentary that would interrupt the flow of the main paragraph.\n- **Bibliography (or References list):** A comprehensive list placed at the end of the document detailing full publication information (Author, Title, Journal, Year, etc.) for every source cited in the text.",

"rm-5-xwnjlv": "# Key Sections of a Research Report\n\n1. **Title Page:** Contains the title, author(s), institution, and date. Identifies the document.\n2. **Abstract/Executive Summary:** A brief summary of the entire study (problem, method, results, conclusion). Allows readers to quickly decide if the report is relevant.\n3. **Introduction:** States the research problem, objectives, hypothesis, and significance. Sets the context.\n4. **Literature Review:** Summarizes relevant past research and identifies the gap this study fills.\n5. **Methodology:** Details the research design, sample, data collection, and analysis methods. Enables replication.\n6. **Results/Findings:** Presents the data collected and the outcomes of statistical analysis (using tables/graphs), without interpretation.\n7. **Discussion:** Interprets the results, explains what they mean, compares them to past literature, and acknowledges limitations.\n8. **Conclusion & Recommendations:** Summarizes the main takeaways and suggests actions or future research directions.\n9. **References/Bibliography:** Lists all sources cited in the report.\n10. **Appendices:** Contains supplementary material (questionnaires, raw data tables) too bulky for the main text.",

"rm-5-t706nb": "# Formulation Rules for Writing a Research Report\n\n1. **Clarity and Precision:** Use clear, straightforward language. Avoid unnecessary jargon or ambiguous terms. State findings precisely.\n2. **Objectivity:** Write in an unbiased, neutral tone. Do not let personal opinions color the interpretation of data. Use third-person perspective (avoid \"I\" or \"we\" unless journal guidelines state otherwise).\n3. **Logical Structure:** Ensure a smooth flow of ideas from the introduction through to the conclusion, following standard academic formatting (IMRAD structure: Introduction, Methods, Results, Discussion).\n4. **Accuracy:** Ensure all data, calculations, and citations are completely accurate.\n5. **Conciseness:** Be brief but comprehensive. Exclude irrelevant information that does not directly address the research objectives.\n6. **Proper Formatting:** Strictly adhere to the required citation style (APA, IEEE, MLA) for headings, margins, citations, and references.\n7. **Use of Visuals:** Use tables, charts, and graphs effectively to present complex data, ensuring they are clearly labeled and referenced in the text.",

"rm-5-m4q7rt": "# Research Metrics and Academic Performance\n\nResearch metrics are quantitative measures used to evaluate the quality, impact, and reach of research output and researchers.\n\n### Author-Level Metrics:\n- **h-index:** A metric that measures both the productivity and citation impact of an author. An h-index of $h$ means the researcher has published $h$ papers that have each been cited at least $h$ times. It prevents a single highly-cited paper from skewing the evaluation.\n- **i10-index:** The number of publications by an author that have received at least 10 citations (used by Google Scholar).\n- **Total Citations:** The absolute number of times an author's work has been cited by others.\n\n### Journal-Level Metrics:\n- **Journal Impact Factor (JIF):** Measures the average number of citations received in a particular year by articles published in the journal during the two preceding years. High JIF indicates a prestigious journal.\n- **CiteScore:** Similar to JIF but uses a 4-year citation window (used by Scopus).\n\n### Significance:\nThese metrics are heavily used by universities for hiring, tenure, and promotion decisions. Funding agencies use them to award grants. They provide an objective (though sometimes flawed) way to measure academic influence."
};

Object.assign(answersData, n);
fs.writeFileSync('./answers.js', `const answersData = ${JSON.stringify(answersData, null, 2)};`);
console.log(`Merged ${Object.keys(n).length} new. Total: ${Object.keys(answersData).length}`);
